[workspace]
members = [
  "the-rust-programming-language/01-getting-started",
  "the-rust-programming-language/02-programming-a-guessing-game",
  "the-rust-programming-language/03-common-programming-concepts"
]
